### ISSUE TITLE
Missing documentation on available data/metrics?

### ISSUE THREAD

**Issue by MA3CIN** [open-telemetry/opentelemetry-network#257]
### Is your feature request related to a problem? Please describe.

I'd love to see in any of the README.md files a section about what data this project (or any of the 4 individual components) can give me. I've went through the readme files (reducer, kernel-collector, cloud-collector, k8s-collector) and only the reducer mentions choosing metrics, without listing all of the available metrics.

### Describe the solution you'd like

A readme section detailing available data and insights

**Comment by MA3CIN** [comment]
Sort of connected to https://github.com/open-telemetry/opentelemetry-network/issues/242 - a new user has little idea what can information can be gained by leveraging these tools, and adding information about the capabilities could bring even more interest in this project

**Comment by yonch** [comment]
Hi @MA3CIN!
Thanks for reporting this. Agree the main README should link to this info.

Does the file docs/metrics/metrics.yaml have what you’re looking for?

**Comment by MA3CIN** [comment]
Hi @yonch, thanks for answering the question
For the most part it does! I see that most of the metrics are in the gauge and counter formats, I'm guessing these are compatible with Prometheus. Is the granularity level adjustable? I imagine that these counters are on the network granularity level (only 1 value per counter per machine that is running these tools, reducer, kernel-collector, etc).
I'd love to get the tcp.rtt values between two pods of my choice, but I'm not sure what output tcp.rtt.average will provide (single gauge).

**Comment by yonch** [comment]
The granularity is adjustable system-wide, see the [reducer flags doc](https://github.com/open-telemetry/opentelemetry-network/blob/main/docs/reducer.md#feature-flags). 

There are three levels of cardinality. These didn't fit Kubernetes naming and so the code (unfortunately) has the following naming:
- "role" is per service
- "az" is per (service, az) pair
- "id" is per pod, which you could think of as (service, az, pod, container, process) since the pod includes that metadata.

Since networks metrics are two-sided (e.g., client and server), the cardinality can increase significantly with added granularity. The reducer by default outputs "az-az" aggregations, but you can turn on "az-id" aggregations or "id-id" which is the pod granularity. Depending on the cluster size, expect *a lot* of time-series.

So specifically, with "id-id" granularity, you could expect tcp.rtt.average for every pair of pods communicating.

You should be able to specify those feature flags in the helm chart under the `reducer.extraArgs` config ([see here](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/af4b111eb32cdf2aa401f02fa8048340130a2f3d/charts/opentelemetry-ebpf/templates/reducer-deployment.yaml#L62)).

**Comment by yonch** [comment]
hope this resolves your question! closing this issue, please re-open if this didn't cover everything
